DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    userid VARCHAR(36) NOT NULL UNIQUE,
    username VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(319) NOT NULL UNIQUE,
    password_hash VARCHAR(60) NOT NULL
);